=== Scratchy2/batelu/src/pages/words.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "word": {
        "type": "string",
        "description": "The word in Batelu."
      },
      "definition": {
        "type": "string",
        "description": "The word's meaning in English."
      },
      "etymology": {
        "oneOf": [
          { "enum": [false] },
          {
            "type": "array",
            "prefixItems": [
              { "type": "string" },
              {
                "oneOf": [
                  { "type": "string" },
                  {
                    "type": "array",
                    "prefixItems": [{ "type": "string" }, { "type": "string" }]
                  }
                ]
              },
              { "type": "string" }
            ]
          }
        ],
        "description": "The word's etymology.\nIn the format of [\"Language\", [\"word\", \"transcription\"], \"meaning\"].\nIf the language already uses the Latin script, the format is [\"Language\", \"word\", \"meaning\"].\nIf the word is a priori, use false.\nIf the source language is Batelu or English, don't put a meaning."
      },
      "type": {
        "enum": [
          "noun",
          "verb",
          "particle",
          "interjection",
          "modifier",
          "numeral",
          "adposition",
          "conjunction"
        ],
        "description": "The part of speech of the word."
      },
      "date": {
        "type": "string",
        "pattern": "^\\d\\d-\\d\\d-\\d\\d\\d\\d$",
        "description": "The date the word's poll closed, after all tiebreakers.\nIn DD-MM-YYYY format."
      }
    },
    "required": ["word", "definition", "etymology", "type", "date"],
    "additionalProperties": false
  }
}

=== Scratchy2/batelu/src/pages/words.json
[
  {
    "word": "baxen",
    "definition": "language",
    "etymology": ["German", "Sprachen", "languages"],
    "type": "noun",
    "date": "07-05-2025"
  },
  {
    "word": "wabi",
    "definition": "fish, sea creature, marine animal",
    "etymology": false,
    "type": "noun",
    "date": "08-05-2025"
  },
  {
    "word": "ludina",
    "definition": "person, human being",
    "etymology": ["Ukrainian", ["людина", "lyudyna"], "person, man"],
    "type": "noun",
    "date": "08-05-2025"
  },
  {
    "word": "tesa",
    "definition": "want, wish, desire",
    "etymology": ["Welsh", "eisiau", "want"],
    "type": "noun",
    "date": "11-05-2025"
  },
  {
    "word": "zol",
    "definition": "soil, ground, earth",
    "etymology": ["French", "sol", "ground, soil"],
    "type": "noun",
    "date": "11-05-2025"
  },
  {
    "word": "zhu",
    "definition": "tree, bush, plant that bears fruit",
    "etymology": false,
    "type": "noun",
    "date": "13-05-2025"
  },
  {
    "word": "batelu",
    "definition": "Batelu",
    "etymology": ["Batelu", "baxen tesa ludina"],
    "type": "noun",
    "date": "13-05-2025"
  },
  {
    "word": "kip",
    "definition": "stone, rock",
    "etymology": ["Afrikaans", "klip", "stone"],
    "type": "noun",
    "date": "14-05-2025"
  },
  {
    "word": "tesare",
    "definition": "to want, to desire",
    "etymology": ["Welsh", "eisiau", "want"],
    "type": "verb",
    "date": "16-05-2025"
  },
  {
    "word": "onore",
    "definition": "to be",
    "etymology": ["Finnish", "on", "there is"],
    "type": "verb",
    "date": "18-05-2025"
  },
  {
    "word": "katare",
    "definition": "to communicate, to speak, to talk",
    "etymology": ["Japanese", ["語る", "kataru"], "speak"],
    "type": "verb",
    "date": "28-05-2025"
  },
  {
    "word": "jesere",
    "definition": "to eat, to drink, to consume",
    "etymology": ["Polish", "jeść", "eat"],
    "type": "verb",
    "date": "29-05-2025"
  },
  {
    "word": "ko",
    "definition": "[question particle]",
    "etymology": ["Finnish", "ko"],
    "type": "particle",
    "date": "31-05-2025"
  },
  {
    "word": "languren",
    "definition": "anthropomorphic animal, furry or relating to the furry fandom",
    "etymology": ["Mandarin Chinese", ["狼人", "lángrén"], "werewolf"],
    "type": "noun",
    "date": "09-06-2025"
  },
  {
    "word": "vi",
    "definition": "air, wind, sky",
    "etymology": false,
    "type": "noun",
    "date": "21-06-2025"
  },
  {
    "word": "poghu",
    "definition": "ability, capability",
    "etymology": ["Catalan", "poguer", "to be able to"],
    "type": "noun",
    "date": "23-06-2025"
  },
  {
    "word": "poghure",
    "definition": "to be able to",
    "etymology": ["Catalan", "poguer", "to be able to"],
    "type": "verb",
    "date": "23-06-2025"
  },
  {
    "word": "cizujo",
    "definition": "need, requirement, something necessary",
    "etymology": ["Japanese", ["必用", "hitsuyō"], "need"],
    "type": "noun",
    "date": "23-06-2025"
  },
  {
    "word": "cizujore",
    "definition": "to need, to require, to have to",
    "etymology": ["Japanese", ["必用", "hitsuyō"], "need"],
    "type": "verb",
    "date": "23-06-2025",
    "usage": "Can be used with either nouns or infinitives."
  },
  {
    "word": "lios",
    "definition": "light, light source, glow, brightness",
    "etymology": ["Faroese", "ljós", "light"],
    "type": "noun",
    "date": "29-06-2025"
  },
  {
    "word": "wakta",
    "definition": "time",
    "etymology": ["Arabic", ["وقت", "waqt"], "time"],
    "type": "noun",
    "date": "23-09-2025"
  },
  {
    "word": "tote",
    "definition": "all, everything",
    "etymology": ["Romanian", "toate", "all"],
    "type": "noun",
    "date": "23-09-2025"
  },
  {
    "word": "sego",
    "definition": "second (time)",
    "etymology": ["Spanish", "segundo", "second"],
    "type": "noun",
    "date": "28-09-2025"
  },
  {
    "word": "kurva",
    "definition": "(UNFINISHED) some sort of sex related word",
    "etymology": ["Polish", "kurwa", "bitch, whore"],
    "type": "noun",
    "date": "09-10-2025"
  },
  {
    "word": "karka",
    "definition": "(vulgar) fuck, shit, other vulgar interjections, (makes other words vulgar as a suffix)",
    "etymology": ["English", "Karkat Vantas", "a Homestuck character"],
    "type": "interjection",
    "date": "09-10-2025"
  },
  {
    "word": "ryvol",
    "definition": "curve, bend, turn",
    "etymology": ["Catalan", "revolt", "turn around"],
    "type": "noun",
    "date": "09-10-2025"
  },
  {
    "word": "neje",
    "definition": "close, nearby, in the vicinity",
    "etymology": ["German", "Nähe", "vicinity"],
    "type": "modifier",
    "date": "10-10-2025"
  },
  {
    "word": "bun",
    "definition": "minute (time)",
    "etymology": ["Japanese", ["分", "bun"], "minute"],
    "type": "noun",
    "date": "11-10-2025"
  },
  {
    "word": "sat",
    "definition": "hour (time)",
    "etymology": ["Croatian", "sat", "hour"],
    "type": "noun",
    "date": "20-10-2025"
  },
  {
    "word": "xuga",
    "definition": "game",
    "etymology": ["Spanish", "jugar", "to play"],
    "type": "noun",
    "date": "04-01-2026"
  },
  {
    "word": "xugare",
    "definition": "to play",
    "etymology": ["Spanish", "jugar", "to play"],
    "type": "verb",
    "date": "04-01-2026"
  },
  {
    "word": "buf",
    "definition": "food",
    "etymology": ["French", "bouffe", "food"],
    "type": "noun",
    "date": "04-01-2026"
  },
  {
    "word": "bon",
    "definition": "good",
    "etymology": ["French", "bonne", "good"],
    "type": "modifier",
    "date": "04-01-2026"
  },
  {
    "word": "mawyr",
    "definition": "cat",
    "etymology": ["Mandarin Chinese", ["猫儿", "māor"], "cat"],
    "type": "noun",
    "date": "05-01-2026"
  },
  {
    "word": "sini",
    "definition": "true, real, existing",
    "etymology": ["Russian", ["истинный", "istinnyy"], "true"],
    "type": "modifier",
    "date": "05-01-2026"
  },
  {
    "word": "citami",
    "definition": "pain",
    "etymology": ["Japanese", ["痛み", "itami"], "pain"],
    "type": "noun",
    "date": "05-01-2026"
  },
  {
    "word": "soj",
    "definition": "water",
    "etymology": ["Cantonese", ["水", "seoi2"], "water"],
    "type": "noun",
    "date": "05-01-2026"
  },
  {
    "word": "dija",
    "definition": "day (measure of time)",
    "etymology": ["Spanish", "día", "day"],
    "type": "noun",
    "date": "05-01-2026"
  },
  {
    "word": "dijabon",
    "definition": "hello, greetings, (literally) good day",
    "etymology": ["Batelu", "dija bon"],
    "type": "interjection",
    "date": "05-01-2026"
  },
  {
    "word": "kaban",
    "definition": "bed",
    "etymology": ["Haitian Creole", "kabann", "bed"],
    "type": "noun",
    "date": "07-01-2026"
  },
  {
    "word": "kabanare",
    "definition": "to sleep, to rest",
    "etymology": ["Batelu", "kaban"],
    "type": "verb",
    "date": "07-01-2026"
  },
  {
    "word": "maku",
    "definition": "mother",
    "etymology": ["Hawaiian", "makuahine", "mother"],
    "type": "noun",
    "date": "07-01-2026"
  },
  {
    "word": "nezh",
    "definition": "snow",
    "etymology": ["French", "neige", "snow"],
    "type": "noun",
    "date": "07-01-2026"
  },
  {
    "word": "xefyl",
    "definition": "drug, medicine",
    "etymology": ["Proto-Indo-European", "*h₂ébōl", "apple"],
    "type": "noun",
    "date": "14-01-2026"
  },
  {
    "word": "wanija",
    "definition": "unstable, moving unnaturally, jittery",
    "etymology": ["Old English", "wandrian", "to wander"],
    "type": "modifier",
    "date": "14-01-2026"
  },
  {
    "word": "wanijare",
    "definition": "to jitter, to shake, to move unnaturally",
    "etymology": ["Batelu", "wanija"],
    "type": "verb",
    "date": "14-01-2026"
  },
  {
    "word": "pentu",
    "definition": "pencil, pen, (physical) writing device",
    "etymology": ["English", "pencil"],
    "type": "noun",
    "date": "16-01-2026"
  },
  {
    "word": "va",
    "definition": "what, which",
    "etymology": ["Norwegian", "hva", "what"],
    "type": "modifier",
    "date": "16-01-2026"
  },
  {
    "word": "va2",
    "definition": "(placeholder for missing info), what",
    "etymology": ["Norwegian", "hva", "what"],
    "type": "particle",
    "date": "16-01-2026"
  },
  {
    "word": "mesi",
    "definition": "thank you",
    "etymology": ["French", "merci", "thank you"],
    "type": "interjection",
    "date": "17-01-2026"
  },
  {
    "word": "byr",
    "definition": "no, not, (negation word)",
    "etymology": ["Serbian", "бр", "no"],
    "type": "modifier",
    "date": "17-01-2026"
  },
  {
    "word": "ori",
    "definition": "this, that, (reflexive pronoun)",
    "etymology": ["Basque", "hori", "that"],
    "type": "modifier",
    "date": "18-01-2026"
  },
  {
    "word": "citamire",
    "definition": "to hurt, to harm, to damage",
    "etymology": ["Batelu", "citami"],
    "type": "verb",
    "date": "18-01-2026"
  },
  {
    "word": "banzhi",
    "definition": "wide",
    "etymology": ["Zulu", "banzi", "wide"],
    "type": "modifier",
    "date": "18-01-2026"
  },
  {
    "word": "ad",
    "definition": "one",
    "etymology": ["Hebrew", ["אֶחָד", "ahad"], "one"],
    "type": "numeral",
    "date": "18-01-2026"
  },
  {
    "word": "ej",
    "definition": "(vocative particle, before noun)",
    "etymology": ["Ukrainian", ["ей", "ey"], "hey"],
    "type": "particle",
    "date": "19-01-2026"
  },
  {
    "word": "do",
    "definition": "two",
    "etymology": ["Hindi", ["दो", "do"], "two"],
    "type": "numeral",
    "date": "19-01-2026"
  },
  {
    "word": "ena",
    "definition": "(indefinite article)",
    "etymology": ["Greek", ["ένα", "ena"], "a"],
    "type": "particle",
    "date": "20-01-2026"
  },
  {
    "word": "al",
    "definition": "(definite article)",
    "etymology": ["Arabic", ["ال", "al"], "the"],
    "type": "particle",
    "date": "20-01-2026"
  },
  {
    "word": "nimra",
